name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    if: ${{ !contains(github.event.head_commit.message, 'Update image tag in values helm') }}
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup GO
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'

    - name: Generate SHA
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Login into the container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          eugustavo/nlw-journey-api:${{steps.generate_sha.outputs.sha}}
          eugustavo/nlw-journey-api:latest

    - name: Update image helm
      uses: fjogeleit/yaml-update-action@main
      with:
        branch: release
        targetBranch: main
        createPR: true
        valueFile: 'k8s-helm/values.yaml'
        propertyPath: 'image.tag'
        value: ${{steps.generate_sha.outputs.sha}}
        commitChange: true
        message: '[skip-ci] Update image tag in values helm'
        

